import java.util.Date;
import com.tlm.beans.*
import com.tlm.utils.*
import javax.activation.MimetypesFileTypeMap
import org.codehaus.groovy.grails.commons.ApplicationHolder

class BootStrap {
	
	def init = { servletContext ->      
		
		//BootstrapUtil.tune(servletContext)
//		File layoutFolder = ApplicationHolder.application.parentContext.getResource("").file 
//		def f1= new File('web-app')
//		def prefix=layoutFolder.absolutePath+'/'
//		def adminUser= User.get(1)
//		if (!adminUser) {
//			def afghanistan = new Country(code:"AFGH",title:"Afghanistan",image:"Afghanistan.png").save()
//			def albania = new Country(code:"ALBA",title:"Albania",image:"Albania.png").save()
//			new Country(code:"ALGE",title:"Algeria",image:"Algeria.png").save()
//			new Country(code:"AMER",title:"American Samoa",image:"American_Samoa.png").save()
//			new Country(code:"ANDO",title:"Andorra",image:"Andorra.png").save()
//			new Country(code:"ANGO",title:"Angola",image:"Angola.png").save()
//			new Country(code:"ANGU",title:"Anguilla",image:"Anguilla.png").save()
//			new Country(code:"ANTI",title:"Antigua and Barbuda",image:"Antigua_and_Barbuda.png").save()
//			new Country(code:"ARGE",title:"Argentina",image:"Argentina.png").save()
//			new Country(code:"ARME",title:"Armenia",image:"Armenia.png").save()
//			new Country(code:"ARUB",title:"Aruba",image:"Aruba.png").save()
//			new Country(code:"AUST",title:"Australia",image:"Australia.png").save()
//			new Country(code:"AUSI",title:"Austria",image:"Austria.png").save()
//			new Country(code:"AZER",title:"Azerbaijan",image:"Azerbaijan.png").save()
//			new Country(code:"BAHA",title:"Bahamas",image:"Bahamas.png").save()
//			new Country(code:"BAHR",title:"Bahrain",image:"Bahrain.png").save()
//			new Country(code:"BANG",title:"Bangladesh",image:"Bangladesh.png").save()
//			new Country(code:"BARB",title:"Barbados",image:"Barbados.png").save()
//			new Country(code:"BELA",title:"Belarus",image:"Belarus.png").save()
//			new Country(code:"BELG",title:"Belgium",image:"Belgium.png").save()
//			new Country(code:"BELI",title:"Belize",image:"Belize.png").save()
//			new Country(code:"BENI",title:"Benin",image:"Benin.png").save()
//			new Country(code:"BERM",title:"Bermuda",image:"Bermuda.png").save()
//			new Country(code:"BHUT",title:"Bhutan",image:"Bhutan.png").save()
//			new Country(code:"BOLI",title:"Bolivia",image:"Bolivia.png").save()
//			new Country(code:"BOSN",title:"Bosnia",image:"Bosnia.png").save()
//			new Country(code:"BOTS",title:"Botswana",image:"Botswana.png").save()
//			new Country(code:"BRAZ",title:"Brazil",image:"Brazil.png").save()
//			new Country(code:"BRIT",title:"British Virgin Islands",image:"British_Virgin_Islands.png").save()
//			new Country(code:"BRUN",title:"Brunei",image:"Brunei.png").save()
//			new Country(code:"BULG",title:"Bulgaria",image:"Bulgaria.png").save()
//			new Country(code:"BURK",title:"Burkina Faso",image:"Burkina_Faso.png").save()
//			new Country(code:"BURU",title:"Burundi",image:"Burundi.png").save()
//			new Country(code:"CAMB",title:"Cambodia",image:"Cambodia.png").save()
//			new Country(code:"CAME",title:"Cameroon",image:"Cameroon.png").save()
//			new Country(code:"CANA",title:"Canada",image:"Canada.png").save()
//			new Country(code:"CAPE",title:"Cape Verde",image:"Cape_Verde.png").save()
//			new Country(code:"CAYM",title:"Cayman Islands",image:"Cayman_Islands.png").save()
//			new Country(code:"CENT",title:"Central African Republic",image:"Central_African_Republic.png").save()
//			new Country(code:"CHAD",title:"Chad",image:"Chad.png").save()
//			new Country(code:"CHIL",title:"Chile",image:"Chile.png").save()
//			new Country(code:"CHIN",title:"China",image:"China.png").save()
//			new Country(code:"CHRI",title:"Christmas Island",image:"Christmas_Island.png").save()
//			new Country(code:"C�T",title:"C�te d'Ivoire",image:"Cite_d'Ivoire.png").save()
//			new Country(code:"COLO",title:"Colombia",image:"Colombia.png").save()
//			new Country(code:"COMO",title:"Comoros",image:"Comoros.png").save()
//			new Country(code:"COOK",title:"Cook Islands",image:"Cook_Islands.png").save()
//			new Country(code:"COST",title:"Costa Rica",image:"Costa_Rica.png").save()
//			new Country(code:"CROA",title:"Croatia",image:"Croatia.png").save()
//			new Country(code:"CUBA",title:"Cuba",image:"Cuba.png").save()
//			new Country(code:"CYPR",title:"Cyprus",image:"Cyprus.png").save()
//			new Country(code:"CYPR",title:"Cyprus Northern",image:"Cyprus_Northern.png").save()
//			new Country(code:"CZEC",title:"Czech Republic",image:"Czech_Republic.png").save()
//			new Country(code:"DEMO",title:"Democratic Republic of the Congo",image:"Democratic_Republic_of_the_Congo.png").save()
//			new Country(code:"DENM",title:"Denmark",image:"Denmark.png").save()
//			new Country(code:"DJIB",title:"Djibouti",image:"Djibouti.png").save()
//			new Country(code:"DOMI",title:"Dominica",image:"Dominica.png").save()
//			new Country(code:"DOMI",title:"Dominican Republic",image:"Dominican_Republic.png").save()
//			new Country(code:"ECUA",title:"Ecuador",image:"Ecuador.png").save()
//			new Country(code:"EGYP",title:"Egypt",image:"Egypt.png").save()
//			new Country(code:"ELSA",title:"El Salvador",image:"El_Salvador.png").save()
//			new Country(code:"EQUA",title:"Equatorial Guinea",image:"Equatorial_Guinea.png").save()
//			new Country(code:"ERIT",title:"Eritrea",image:"Eritrea.png").save()
//			new Country(code:"ESTO",title:"Estonia",image:"Estonia.png").save()
//			new Country(code:"ETHI",title:"Ethiopia",image:"Ethiopia.png").save()
//			new Country(code:"FALK",title:"Falkland Islands",image:"Falkland_Islands.png").save()
//			new Country(code:"FARO",title:"Faroe Islands",image:"Faroe_Islands.png").save()
//			new Country(code:"FIJI",title:"Fiji",image:"Fiji.png").save()
//			new Country(code:"FINL",title:"Finland",image:"Finland.png").save()
//			new Country(code:"FRAN",title:"France",image:"France.png").save()
//			new Country(code:"FREN",title:"French Polynesia",image:"French_Polynesia.png").save()
//			new Country(code:"GABO",title:"Gabon",image:"Gabon.png").save()
//			new Country(code:"GAMB",title:"Gambia",image:"Gambia.png").save()
//			new Country(code:"GEOR",title:"Georgia",image:"Georgia.png").save()
//			new Country(code:"GERM",title:"Germany",image:"Germany.png").save()
//			new Country(code:"GHAN",title:"Ghana",image:"Ghana.png").save()
//			new Country(code:"GIBR",title:"Gibraltar",image:"Gibraltar.png").save()
//			new Country(code:"GREE",title:"Greece",image:"Greece.png").save()
//			new Country(code:"GREE",title:"Greenland",image:"Greenland.png").save()
//			new Country(code:"GREN",title:"Grenada",image:"Grenada.png").save()
//			new Country(code:"GUAM",title:"Guam",image:"Guam.png").save()
//			new Country(code:"GUAT",title:"Guatemala",image:"Guatemala.png").save()
//			new Country(code:"GUIN",title:"Guinea",image:"Guinea.png").save()
//			new Country(code:"GUIN",title:"Guinea Bissau",image:"Guinea_Bissau.png").save()
//			new Country(code:"GUYA",title:"Guyana",image:"Guyana.png").save()
//			new Country(code:"HAIT",title:"Haiti",image:"Haiti.png").save()
//			new Country(code:"HOND",title:"Honduras",image:"Honduras.png").save()
//			new Country(code:"HONG",title:"Hong Kong",image:"Hong_Kong.png").save()
//			new Country(code:"HUNG",title:"Hungary",image:"Hungary.png").save()
//			new Country(code:"ICEL",title:"Iceland",image:"Iceland.png").save()
//			new Country(code:"INDI",title:"India",image:"India.png").save()
//			new Country(code:"INDO",title:"Indonesia",image:"Indonesia.png").save()
//			new Country(code:"IRAN",title:"Iran",image:"Iran.png").save()
//			new Country(code:"IRAQ",title:"Iraq",image:"Iraq.png").save()
//			new Country(code:"IREL",title:"Ireland",image:"Ireland.png").save()
//			new Country(code:"ISRA",title:"Israel",image:"Israel.png").save()
//			new Country(code:"ITAL",title:"Italy",image:"Italy.png").save()
//			new Country(code:"JAMA",title:"Jamaica",image:"Jamaica.png").save()
//			new Country(code:"JAPA",title:"Japan",image:"Japan.png").save()
//			new Country(code:"JORD",title:"Jordan",image:"Jordan.png").save()
//			new Country(code:"KAZA",title:"Kazakhstan",image:"Kazakhstan.png").save()
//			new Country(code:"KENY",title:"Kenya",image:"Kenya.png").save()
//			new Country(code:"KIRI",title:"Kiribati",image:"Kiribati.png").save()
//			new Country(code:"KUWA",title:"Kuwait",image:"Kuwait.png").save()
//			new Country(code:"KYRG",title:"Kyrgyzstan",image:"Kyrgyzstan.png").save()
//			new Country(code:"LAOS",title:"Laos",image:"Laos.png").save()
//			new Country(code:"LATV",title:"Latvia",image:"Latvia.png").save()
//			new Country(code:"LEBA",title:"Lebanon",image:"Lebanon.png").save()
//			new Country(code:"LESO",title:"Lesotho",image:"Lesotho.png").save()
//			new Country(code:"LIBE",title:"Liberia",image:"Liberia.png").save()
//			new Country(code:"LIBY",title:"Libya",image:"Libya.png").save()
//			new Country(code:"LIEC",title:"Liechtenstein",image:"Liechtenstein.png").save()
//			new Country(code:"LITH",title:"Lithuania",image:"Lithuania.png").save()
//			new Country(code:"LUXE",title:"Luxembourg",image:"Luxembourg.png").save()
//			new Country(code:"MACA",title:"Macao",image:"Macao.png").save()
//			new Country(code:"MACE",title:"Macedonia",image:"Macedonia.png").save()
//			new Country(code:"MADA",title:"Madagascar",image:"Madagascar.png").save()
//			new Country(code:"MALA",title:"Malawi",image:"Malawi.png").save()
//			new Country(code:"MALA",title:"Malaysia",image:"Malaysia.png").save()
//			new Country(code:"MALD",title:"Maldives",image:"Maldives.png").save()
//			new Country(code:"MALI",title:"Mali",image:"Mali.png").save()
//			new Country(code:"MALT",title:"Malta",image:"Malta.png").save()
//			new Country(code:"MARS",title:"Marshall Islands",image:"Marshall_Islands.png").save()
//			new Country(code:"MART",title:"Martinique",image:"Martinique.png").save()
//			new Country(code:"MAUR",title:"Mauritania",image:"Mauritania.png").save()
//			new Country(code:"MAUR",title:"Mauritius",image:"Mauritius.png").save()
//			new Country(code:"MEXI",title:"Mexico",image:"Mexico.png").save()
//			new Country(code:"MICR",title:"Micronesia",image:"Micronesia.png").save()
//			new Country(code:"MOLD",title:"Moldova",image:"Moldova.png").save()
//			new Country(code:"MONA",title:"Monaco",image:"Monaco.png").save()
//			new Country(code:"MONG",title:"Mongolia",image:"Mongolia.png").save()
//			new Country(code:"MONT",title:"Montserrat",image:"Montserrat.png").save()
//			new Country(code:"MORO",title:"Morocco",image:"Morocco.png").save()
//			new Country(code:"MOZA",title:"Mozambique",image:"Mozambique.png").save()
//			new Country(code:"MYAN",title:"Myanmar",image:"Myanmar.png").save()
//			new Country(code:"NAMI",title:"Namibia",image:"Namibia.png").save()
//			new Country(code:"NAUR",title:"Nauru",image:"Nauru.png").save()
//			new Country(code:"NEPA",title:"Nepal",image:"Nepal.png").save()
//			new Country(code:"NETH",title:"Netherlands",image:"Netherlands.png").save()
//			new Country(code:"NETH",title:"Netherlands Antilles",image:"Netherlands_Antilles.png").save()
//			new Country(code:"NEWZ",title:"New Zealand",image:"New_Zealand.png").save()
//			new Country(code:"NICA",title:"Nicaragua",image:"Nicaragua.png").save()
//			new Country(code:"NIGE",title:"Niger",image:"Niger.png").save()
//			new Country(code:"NIGE",title:"Nigeria",image:"Nigeria.png").save()
//			new Country(code:"NIUE",title:"Niue",image:"Niue.png").save()
//			new Country(code:"NORF",title:"Norfolk Island",image:"Norfolk_Island.png").save()
//			new Country(code:"NORT",title:"North Korea",image:"North_Korea.png").save()
//			new Country(code:"NORW",title:"Norway",image:"Norway.png").save()
//			new Country(code:"OMAN",title:"Oman",image:"Oman.png").save()
//			new Country(code:"PAKI",title:"Pakistan",image:"Pakistan.png").save()
//			new Country(code:"PALA",title:"Palau",image:"Palau.png").save()
//			new Country(code:"PANA",title:"Panama",image:"Panama.png").save()
//			new Country(code:"PAPU",title:"Papua New Guinea",image:"Papua_New_Guinea.png").save()
//			new Country(code:"PARA",title:"Paraguay",image:"Paraguay.png").save()
//			new Country(code:"PERU",title:"Peru",image:"Peru.png").save()
//			new Country(code:"PHIL",title:"Philippines",image:"Philippines.png").save()
//			new Country(code:"PITC",title:"Pitcairn Islands",image:"Pitcairn_Islands.png").save()
//			new Country(code:"POLA",title:"Poland",image:"Poland.png").save()
//			new Country(code:"PORT",title:"Portugal",image:"Portugal.png").save()
//			new Country(code:"PUER",title:"Puerto Rico",image:"Puerto_Rico.png").save()
//			new Country(code:"QATA",title:"Qatar",image:"Qatar.png").save()
//			new Country(code:"REPU",title:"Republic of the Congo",image:"Republic_of_the_Congo.png").save()
//			new Country(code:"ROMA",title:"Romania",image:"Romania.png").save()
//			new Country(code:"RUSS",title:"Russian Federation",image:"Russian_Federation.png").save()
//			new Country(code:"RWAN",title:"Rwanda",image:"Rwanda.png").save()
//			new Country(code:"SAIN",title:"Saint Kitts and Nevis",image:"Saint_Kitts_and_Nevis.png").save()
//			new Country(code:"SAIN",title:"Saint Lucia",image:"Saint_Lucia.png").save()
//			new Country(code:"SAIN",title:"Saint Pierre",image:"Saint_Pierre.png").save()
//			new Country(code:"SAIN",title:"Saint Vicent and the Grenadines",image:"Saint_Vicent_and_the_Grenadines.png").save()
//			new Country(code:"SAMO",title:"Samoa",image:"Samoa.png").save()
//			new Country(code:"SANM",title:"San Marino",image:"San_Marino.png").save()
//			new Country(code:"SAOT",title:"Sao Tome and Principe",image:"Sao Tome and Principe.png").save()
//			new Country(code:"SAUD",title:"Saudi Arabia",image:"Saudi_Arabia.png").save()
//			new Country(code:"SENE",title:"Senegal",image:"Senegal.png").save()
//			new Country(code:"SERB",title:"Serbia and Montenegro",image:"Serbia_and_Montenegro.png").save()
//			new Country(code:"SEYC",title:"Seychelles",image:"Seychelles.png").save()
//			new Country(code:"SIER",title:"Sierra Leone",image:"Sierra_Leone.png").save()
//			def singapore = new Country(code:"SING",title:"Singapore",image:"Singapore.png").save()
//			new Country(code:"SLOV",title:"Slovakia",image:"Slovakia.png").save()
//			new Country(code:"SLOV",title:"Slovenia",image:"Slovenia.png").save()
//			new Country(code:"SOLO",title:"Soloman Islands",image:"Soloman_Islands.png").save()
//			new Country(code:"SOMA",title:"Somalia",image:"Somalia.png").save()
//			new Country(code:"SOUT",title:"South Africa",image:"South_Africa.png").save()
//			new Country(code:"SOUT",title:"South Georgia",image:"South_Georgia.png").save()
//			new Country(code:"SOUT",title:"South Korea",image:"South_Korea.png").save()
//			new Country(code:"SOVI",title:"Soviet Union",image:"Soviet_Union.png").save()
//			new Country(code:"SPAI",title:"Spain",image:"Spain.png").save()
//			new Country(code:"SRIL",title:"Sri Lanka",image:"Sri_Lanka.png").save()
//			new Country(code:"SUDA",title:"Sudan",image:"Sudan.png").save()
//			new Country(code:"SURI",title:"Suriname",image:"Suriname.png").save()
//			new Country(code:"SWAZ",title:"Swaziland",image:"Swaziland.png").save()
//			new Country(code:"SWED",title:"Sweden",image:"Sweden.png").save()
//			new Country(code:"SWIT",title:"Switzerland",image:"Switzerland.png").save()
//			new Country(code:"SYRI",title:"Syria",image:"Syria.png").save()
//			new Country(code:"TAIW",title:"Taiwan",image:"Taiwan.png").save()
//			new Country(code:"TAJI",title:"Tajikistan",image:"Tajikistan.png").save()
//			new Country(code:"TANZ",title:"Tanzania",image:"Tanzania.png").save()
//			new Country(code:"THAI",title:"Thailand",image:"Thailand.png").save()
//			new Country(code:"TIBE",title:"Tibet",image:"Tibet.png").save()
//			new Country(code:"TIMO",title:"Timor-Leste",image:"Timor-Leste.png").save()
//			new Country(code:"TOGO",title:"Togo",image:"Togo.png").save()
//			new Country(code:"TONG",title:"Tonga",image:"Tonga.png").save()
//			new Country(code:"TRIN",title:"Trinidad and Tobago",image:"Trinidad_and_Tobago.png").save()
//			new Country(code:"TUNI",title:"Tunisia",image:"Tunisia.png").save()
//			new Country(code:"TURK",title:"Turkey",image:"Turkey.png").save()
//			new Country(code:"TURK",title:"Turkmenistan",image:"Turkmenistan.png").save()
//			new Country(code:"TURK",title:"Turks and Caicos Islands",image:"Turks_and_Caicos_Islands.png").save()
//			new Country(code:"TUVA",title:"Tuvalu",image:"Tuvalu.png").save()
//			new Country(code:"UAE",title:"UAE",image:"UAE.png").save()
//			new Country(code:"USVI",title:"US Virgin Islands",image:"US_Virgin_Islands.png").save()
//			new Country(code:"UGAN",title:"Uganda",image:"Uganda.png").save()
//			new Country(code:"UKRA",title:"Ukraine",image:"Ukraine.png").save()
//			new Country(code:"UNIT",title:"United Kingdom",image:"United_Kingdom.png").save()
//			new Country(code:"UNIT",title:"United States of America",image:"United_States_of_America.png").save()
//			new Country(code:"URUG",title:"Uruguay",image:"Uruguay.png").save()
//			new Country(code:"UZBE",title:"Uzbekistan",image:"Uzbekistan.png").save()
//			new Country(code:"VANU",title:"Vanuatu",image:"Vanuatu.png").save()
//			new Country(code:"VATI",title:"Vatican City",image:"Vatican_City.png").save()
//			new Country(code:"VENE",title:"Venezuela",image:"Venezuela.png").save()
//			new Country(code:"VIET",title:"Vietnam",image:"Vietnam.png").save()
//			new Country(code:"WALL",title:"Wallis and Futuna",image:"Wallis_and_Futuna.png").save()
//			new Country(code:"YEME",title:"Yemen",image:"Yemen.png").save()
//			new Country(code:"ZAMB",title:"Zambia",image:"Zambia.png").save()
//			new Country(code:"ZIMB",title:"Zimbabwe",image:"Zimbabwe.png").save()
//			
//			
//			def admin = new JobPosition(title: 'Admin / General Services').save()
//			def ceo = new JobPosition(title: 'CEO /Managing Director').save()
//			new JobPosition(title: 'Director').save()
//			new JobPosition(title: 'General Manager').save()
//			new JobPosition(title: 'Buyer').save()
//			new JobPosition(title: 'Exports').save()
//			new JobPosition(title: 'Executive').save()
//			new JobPosition(title: 'Maintenance / Servicing').save()
//			new JobPosition(title: 'Technical Lead').save()
//			new JobPosition(title: 'Managerial').save()
//			new JobPosition(title: 'Marketing Communications').save()
//			new JobPosition(title: 'Purchasing').save()
//			new JobPosition(title: 'R & D / Quality Control').save()
//			new JobPosition(title: 'Sales Representative').save()
//			new JobPosition(title: 'Technician / Engineers').save()
//			new JobPosition(title: 'Others').save()
//			
//			
//			def agent = new JobFunction(title:'Agents / Distributor').save()
//			def architect = new JobFunction(title:'Architect').save()
//			new JobFunction(title:'Association / Organisation').save()
//			new JobFunction(title:'Bathroom Designer').save()
//			new JobFunction(title:'Civil & Structural Engineer').save()
//			new JobFunction(title:'Consultant').save()
//			new JobFunction(title:'Facility / Property Manager').save()
//			new JobFunction(title:'Fire Safety Manager').save()
//			new JobFunction(title:'Government Agency').save()
//			new JobFunction(title:'Interior Designer').save()
//			new JobFunction(title:'Landscape Architect').save()
//			new JobFunction(title:'Lighting Designer').save()
//			new JobFunction(title:'M & E Engineer').save()
//			new JobFunction(title:'Main Contractor').save()
//			new JobFunction(title:'Media / Advertising Agency').save()
//			new JobFunction(title:'Project Manager').save()
//			new JobFunction(title:'Quantity Surveyor').save()
//			new JobFunction(title:'Retailer / Hotelier').save()
//			new JobFunction(title:'Security Manager').save()
//			new JobFunction(title:'Security Service Company').save()
//			new JobFunction(title:'Sub Contractor').save()
//			new JobFunction(title:'Suppliers / Manufacturer').save()
//			new JobFunction(title:'Others').save()
//			def mr = new LookupHonorific(type:'Mr').save()
//			new LookupHonorific(type:'Miss').save()
//			new LookupHonorific(type:'Mrs').save()
//			new LookupHonorific(type:'Ms').save()
//			new LookupHonorific(type:'Dr').save()
//			
//			def pdfService = new Service(name: 'Publication Announcement Newsletters').save();
//			def adsService = new Service(name: 'Advertisement Newsletters').save();
//			def newsService = new Service(name: 'Weekly Blast Newsletters').save();
//			def services = [pdfService, adsService,newsService]
//			
//			def bt = new Publication(pubId:'1',htmlWriteUp:'',pubLongName:"Bathroom Today",pubShortName:"BT").save()
//			def ct = new Publication(pubId:'2',htmlWriteUp:'',pubLongName:"Concrete Technology Today",pubShortName:"CTT").save()
//			def lt = new Publication(pubId:'3',htmlWriteUp:'',pubLongName:"Landscape Today",pubShortName:"LST").save()
//			def land = new Publication(pubId:'4',htmlWriteUp:'',pubLongName:"Lighting Today",pubShortName:"LT").save()
//			def st = new Publication(pubId:'5',htmlWriteUp:'',pubLongName:"Security Solutions Today",pubShortName:"SST").save()
//			def seab = new Publication(pubId:'6',htmlWriteUp:'',pubLongName:"Southeast Asia Building",pubShortName:"SEAB").save()
//			def seac = new Publication(pubId:'7',htmlWriteUp:'',pubLongName:"Southeast Asia Construction",pubShortName:"SEAC").save()
//			def publications = [bt, ct,lt,land,st,seab,seac]
//			
//			User administrator = new User(userName: 'admin', password: 'password', confirmPassword: 'password', firstName: 'admin', lastName: 'admin', honorific: mr, email: 'test@soho.sg', gender: 'M', country: singapore, telephone: 91234567, accountStatus: User.ACTIVE)
//			administrator.save()
//			
//			
//			
//			publications.each { publication ->
//				services.each { service ->
//					def subscription = new Subscription()
//					subscription.user = administrator
//					subscription.publication = publication
//					subscription.service = service
//					subscription.signupDate = new Date()
//					subscription.subscriptionStatus = "A"
//					
//					subscription.save()
//					administrator.addToSubscriptions(subscription)	
//				}
//			}
//			Role adminRole = new Role(roleName: 'ROLE_ADMIN', description: 'Administrator Account').save()
//			Role subRole = new Role(roleName: 'ROLE_SUBSCRIBER', description: 'Normal Account').save()
//			adminRole.addToUsers(administrator)
//			
//			// permissions for adminRole
//			new RequestMap(url: '/issue/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/user/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/role/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/document/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/emailJob/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/requestMap/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/template/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/ads/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/news/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/admin', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/publication/*', configAttribute: adminRole.roleName).save()
//			new RequestMap(url: '/service/*', configAttribute: adminRole.roleName).save()
//			
//			// 	add mime types to the default mime type map
//			def map = new MimetypesFileTypeMap()
//			map.addMimeTypes("application/pdf pdf")
//			map.addMimeTypes("application/x-shockwave-flash swf")
//			MimetypesFileTypeMap.setDefaultFileTypeMap(map)
//		} // initialize basic data if admin user does not exist
//		
//		log.info "Headless? " + java.awt.GraphicsEnvironment.isHeadless()
//		
//		// create the receptionist role if needed
//		Role recepRole = Role.findByRoleName("ROLE_RECEP")
//		
//		if (!recepRole) {
//			// create the receptionist role
//			log.info "Receptionist role does not exist, creating"
//			recepRole = new Role(roleName: "ROLE_RECEP", description: "Receptionist").save()
//		}
//		
//		// create data entry permissions if needed		
//		RequestMap deAdminPerm = RequestMap.findByUrlAndConfigAttribute("/dataEntry/*", "ROLE_ADMIN,ROLE_RECEP")		
//		if (!deAdminPerm) {
//			log.info "Data Entry permissions absent, creating..."
//			new RequestMap(url: '/dataEntry/*', configAttribute: "ROLE_ADMIN,ROLE_RECEP").save()
//		}
//		deAdminPerm = RequestMap.findByUrlAndConfigAttribute("/recep/*", "ROLE_ADMIN,ROLE_RECEP")
//		if (!deAdminPerm) {
//			log.info "Data Entry permissions absent, creating..."
//			new RequestMap(url: '/recep/*', configAttribute: "ROLE_ADMIN,ROLE_RECEP").save()
//		}
//		deAdminPerm = RequestMap.findByUrlAndConfigAttribute("/searchable/*", "ROLE_ADMIN")
//		if (!deAdminPerm) {
//			log.info "Data Entry permissions absent, creating..."
//			new RequestMap(url: '/searchable/*', configAttribute: "ROLE_ADMIN").save()
//		}
		
		// [241010] Ben: Launch a daemon to monitor the server every minute, logging the memory usage
		//MonitoringUtil.startMonitoring();
		
	}
	
	def destroy = {
	}
}
